service: strmr-video
frameworkVersion: '2'
configValidationMode: error
useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'eu-west-1'}

  environment:
    VIDEOS_TABLE_NAME: ${env:VIDEOS_TABLE_NAME}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource: ${env:VIDEOS_BUCKET_ARN}
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
          Resource: '${env:VIDEOS_BUCKET_ARN}/*'
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Get*'
            - 'dynamodb:Delete*'
            - 'dynamodb:Update*'
            - 'dynamodb:Put*'
          Resource: ${env:VIDEOS_TABLE_ARN}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  upload:
    handler: bin/upload
    events:
      - s3:
          bucket: "strmr-videos-${self:provider.stage}"
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: public/uploads/
